### ISSUE TITLE
Object doesn't support property or method 'getRootNode'

### ISSUE THREAD

**Issue by mintyfloss** [RetailMeNot/fractals#208]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In IE, I see errors with the `DropDown` component.

```
Object doesn't support property or method 'getRootNode'
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

1. Use IE11 and go to https://www.retailmenot.com/.
2. Click login button and login
3. User should be redirected back to https://www.retailmenot.com/
4. After a couple of seconds when the page detects the user is logged in, the header will disappear and the error will be printed in console.

**What is the expected behavior?**

`DropDown` should work in IE

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

-------------------------------

getRootNode isn't supported in IE https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode.

https://github.com/RetailMeNot/anchor/blob/8220f8711a6c5198865b31534f18952fa8560a66/src/DropDown/DropDown.component.tsx#L137

I'm creating this issue because I'm not sure what the real fix should be. It seems like `rootElement` would always be `document`. So could we write the line like

```
// Dropdown Instance
this.rootElement = dropDown ? document : null;
```

Does this use `getRootNode()` because `dropDown` can be inside of a shadow DOM?

**Comment by brandonlilly** [comment]
Fixed in #215
